In [ ]:
## Task 1 Question

# You are given a list of raw transaction records, where each record is a dictionary:

transactions = [
    {"id": 1, "product": "Laptop", "price": 1200, "quantity": 2, "region": "EU"},
    {"id": 2, "product": "Phone", "price": 800, "quantity": -1, "region": "US"},
    {"id": 3, "product": "Tablet", "price": 0, "quantity": 5, "region": "EU"},
    {"id": 4, "product": "Monitor", "price": 350, "quantity": 3, "region": "US"},
    {"id": 5, "product": "Laptop", "price": 1200, "quantity": 1, "region": "EU"},
    {"id": 6, "product": "Keyboard", "price": 75, "quantity": 10, "region": "APAC"},
]
# Write a script that performs the following steps:

# a) Filter out invalid transactions where the price is zero or the quantity is negative.

# b) For each remaining transaction, compute a new field total = price * quantity.

# c) Group the valid transactions by region and compute the total revenue per region. Store the result in a dictionary.

# d) Print the region with the highest total revenue and its value using an f-string.

In [10]:
## Task 1 Solutions

transactions = [
    {"id": 1, "product": "Laptop", "price": 1200, "quantity": 2, "region": "EU"},
    {"id": 2, "product": "Phone", "price": 800, "quantity": -1, "region": "US"},
    {"id": 3, "product": "Tablet", "price": 0, "quantity": 5, "region": "EU"},
    {"id": 4, "product": "Monitor", "price": 350, "quantity": 3, "region": "US"},
    {"id": 5, "product": "Laptop", "price": 1200, "quantity": 1, "region": "EU"},
    {"id": 6, "product": "Keyboard", "price": 75, "quantity": 10, "region": "APAC"},
]

# a)
valid_transactions = []
for t in transactions:
    if t["price"] > 0 and t["quantity"] >= 0:
        valid_transactions.append(t)

# b)
for t in valid_transactions:
    t["total"] = t["price"] * t["quantity"]

# c)
region_totals = {}
for t in valid_transactions:
    region = t["region"]
    if region not in region_totals:
        region_totals[region] = 0
    region_totals[region] = region_totals[region] + t["total"]

# d)
best_region = max(region_totals, key=region_totals.get)
best_value = region_totals[best_region]


print(valid_transactions)
print(region_totals)
print(f"{best_region} has the highest revenue: {best_value}")

[{'id': 1, 'product': 'Laptop', 'price': 1200, 'quantity': 2, 'region': 'EU', 'total': 2400}, {'id': 4, 'product': 'Monitor', 'price': 350, 'quantity': 3, 'region': 'US', 'total': 1050}, {'id': 5, 'product': 'Laptop', 'price': 1200, 'quantity': 1, 'region': 'EU', 'total': 1200}, {'id': 6, 'product': 'Keyboard', 'price': 75, 'quantity': 10, 'region': 'APAC', 'total': 750}]
{'EU': 3600, 'US': 1050, 'APAC': 750}
EU has the highest revenue: 3600


In [ ]:
## Task 2 Questions

# You are given the following list of daily sales figures (in euros) for a two-week period:

sales = [1200, 980, 1540, 870, 2010, 1650, 1300, 1100, 950, 1780, 2200, 1430, 1600, 1900]

# Write a function called summarise_sales that takes a list of daily sales values and returns a dictionary containing:

# "total": the sum of all daily sales

# "average": the mean daily sales value, rounded to two decimals

# "best_day": the index (starting from 1) of the day with the highest sales

# "worst_day": the index (starting from 1) of the day with the lowest sales

# "above_average_count": the number of days where sales exceeded the average

# Call the function with the list above and print the returned dictionary.

In [11]:
## Task 2 Solutions

sales = [1200, 980, 1540, 870, 2010, 1650, 1300, 1100, 950, 1780, 2200, 1430, 1600, 1900]

def summarise_sales(x):
    # Below is the process calculating the above_average_count value
    y = 0
    for i in range(len(x)):
        if x[i] > sum(x) / len(x):
            y = y + 1
            
    # Here is the rest of the function written
    z = {
        "total": sum(x),
        "average": round(sum(x) / len(x),2),
        "best_day": 1 + x.index(max(x)),
        "worst_day": 1 + x.index(min(x)),
        "above_average_count": y}
    return z
    
print(summarise_sales(sales))

{'total': 20510, 'average': 1465.0, 'best_day': 11, 'worst_day': 4, 'above_average_count': 7}
The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.


In [ ]:
## Task 3 Questions

# You are given the following list of student records:

students = [
    {"name": "Anna", "grade": 85, "attendance": 0.92},
    {"name": "Erik", "grade": 58, "attendance": 0.75},
    {"name": "Mia", "grade": 91, "attendance": 0.98},
    {"name": "Leo", "grade": 44, "attendance": 0.60},
    {"name": "Sara", "grade": 72, "attendance": 0.88},
    {"name": "Tom", "grade": 67, "attendance": 0.70},
    {"name": "Nina", "grade": 95, "attendance": 0.99},
    {"name": "Olli", "grade": 50, "attendance": 0.65},
]
# Using for loops and if statements, perform the following:

# a) Create a new list called passing that contains only the names of students with a grade of 50 or above. Print the list.

# b) Loop through the students and print a status message for each. If the student's grade is 80 or above, print "[name]: Excellent"; if between 50 and 79, print "[name]: Pass"; otherwise print "[name]: Fail".

# c) Count how many students have an attendance rate below 0.80. Print the count.

# d) Find the student with the highest grade using a loop (do not use max()). Print the student's name and grade.

# e) Now find the student with the highest grade using max(). Print the student's name and grade.

In [12]:
## Task 3 Solutions

students = [
    {"name": "Anna", "grade": 85, "attendance": 0.92},
    {"name": "Erik", "grade": 58, "attendance": 0.75},
    {"name": "Mia", "grade": 91, "attendance": 0.98},
    {"name": "Leo", "grade": 44, "attendance": 0.60},
    {"name": "Sara", "grade": 72, "attendance": 0.88},
    {"name": "Tom", "grade": 67, "attendance": 0.70},
    {"name": "Nina", "grade": 95, "attendance": 0.99},
    {"name": "Olli", "grade": 50, "attendance": 0.65},
]

# task a
passing = []
for i in range(len(students)):
    if students[i]["grade"] >= 50:
        passing.append(students[i]["name"])
print(passing)

# task b
for i in range(len(students)):
    if students[i]["grade"] >= 80:
        print(f"{students[i]['name']}: Excellent")
    elif students[i]["grade"] >= 50:
        print(f"{students[i]['name']}: Pass")
    else:
        print(f"{students[i]['name']}: Fail")

# task c
count = 0
for i in range(len(students)):
    if students[i]["attendance"] < 0.80:
        count = count + 1
print(count)

# task d
highest = 0
for i in range(len(students)):
    if students[i]["grade"] > students[highest]["grade"]:
        highest = i
print(students[highest]["name"], students[highest]["grade"])

# task e
values = []
for i in range(len(students)):
    values.append(students[i]["grade"])

highest_index = values.index(max(values))
print(students[highest_index]["name"], students[highest_index]["grade"])

['Anna', 'Erik', 'Mia', 'Sara', 'Tom', 'Nina', 'Olli']
Anna: Excellent
Erik: Pass
Mia: Excellent
Leo: Fail
Sara: Pass
Tom: Pass
Nina: Excellent
Olli: Pass
4
Nina 95
Nina 95


In [ ]:
## Task 4 Questions

# Design a class called Portfolio that represents an investment portfolio. The constructor is provided for you:

class Portfolio:
    def __init__(self, owner):
        self.owner = owner
        self.holdings = {}  # ticker -> {shares, price_per_share}
# Each key in holdings is a ticker symbol (string) and each value is a dictionary with keys "shares" and "price_per_share". Add the following methods to the class:

# a) A method add_asset(ticker, shares, price_per_share) that adds a new asset or updates the number of shares if the ticker already exists (in which case the price should also be updated).

# b) A method total_value() that returns the total market value of the portfolio.

# c) A method most_valuable() that returns the ticker of the asset with the highest total value (shares × price).

# d) A __str__ method that returns a readable summary of the portfolio, including the owner's name, the number of assets, and the total value.

# Create an instance, add at least three assets, and demonstrate all methods with printed output.

In [13]:
## Task 4 Solutions

class Portfolio:
    def __init__(self, owner):
        self.owner = owner
        self.holdings = {}

    def add_asset(self, ticker, shares, price_per_share):
        if ticker in self.holdings:
            self.holdings[ticker]["shares"] = self.holdings[ticker]["shares"] + shares
            self.holdings[ticker]["price_per_share"] = price_per_share
        else:
            self.holdings[ticker] = {
                "shares": shares,
                "price_per_share": price_per_share
            }

    def total_value(self):
        total = 0
        for ticker in self.holdings:
            shares = self.holdings[ticker]["shares"]
            price = self.holdings[ticker]["price_per_share"]
            total = total + shares * price
        return total

    def most_valuable(self):
        highest_ticker = ""
        highest_value = 0

        for ticker in self.holdings:
            shares = self.holdings[ticker]["shares"]
            price = self.holdings[ticker]["price_per_share"]
            value = shares * price

            if value > highest_value:
                highest_value = value
                highest_ticker = ticker

        return highest_ticker

    def __str__(self):
        return f"Owner: {self.owner}, Assets: {len(self.holdings)}, Total value: {self.total_value()}"


portfolio = Portfolio("Evert")

portfolio.add_asset("AAPL", 10, 180)
portfolio.add_asset("MSFT", 5, 420)
portfolio.add_asset("TSLA", 8, 250)
portfolio.add_asset("AAPL", 2, 190)

print(portfolio.holdings)
print(portfolio.total_value())
print(portfolio.most_valuable())
print(portfolio)

{'AAPL': {'shares': 12, 'price_per_share': 190}, 'MSFT': {'shares': 5, 'price_per_share': 420}, 'TSLA': {'shares': 8, 'price_per_share': 250}}
6380
AAPL
Owner: Evert, Assets: 3, Total value: 6380


In [ ]:
## Task 5 Questions

# You are given the following list of order dates (as strings) and product names:

orders = [
    ("2025-01-15", "Laptop"), ("2025-01-22", "Phone"),
    ("2025-02-03", "Laptop"), ("2025-02-14", "Tablet"),
    ("2025-03-01", "Phone"), ("2025-03-10", "Phone"),
    ("2025-03-22", "Laptop"), ("2025-04-05", "Monitor"),
]
# Using the datetime module, parse each date string into a datetime.date object. Compute and print the number of days between the earliest and latest order.

In [14]:
## Task 5 Solutions

import datetime as dt

orders = [
    ("2025-01-15", "Laptop"), ("2025-01-22", "Phone"),
    ("2025-02-03", "Laptop"), ("2025-02-14", "Tablet"),
    ("2025-03-01", "Phone"), ("2025-03-10", "Phone"),
    ("2025-03-22", "Laptop"), ("2025-04-05", "Monitor"),
]

dates = []
for order in orders:
    # Using logic: dt.datetime.strptime("2025-01-15", "%Y-%m-%d")
    date = dt.datetime.strptime(order[0], "%Y-%m-%d").date()
    dates.append(date)

difference = max(dates) - min(dates)
print(difference.days)


80


In [ ]:
## Task 6 Questions

# A company tracks quarterly revenue (in thousands of euros) across four quarters over three years:

# Rows: years (2022, 2023, 2024), Columns: quarters (Q1, Q2, Q3, Q4)
revenue = np.array([
    [210, 230, 190, 250],
    [220, 260, 200, 270],
    [250, 290, 230, 310]])
# a) Compute and print the total annual revenue for each year (i.e., row sums). Use the axis parameter.

# b) Compute the mean quarterly revenue across all years (i.e., column means).

# c) Using broadcasting, apply a growth adjustment to the 2024 row by multiplying it element-wise with the array [1.05, 1.03, 1.08, 1.02]. Print the adjusted values.

# d) Use boolean indexing to find and print all quarterly revenue values that exceed 250 (thousands of euros).

In [15]:
## Task 6 Solutions

import numpy as np

revenue = np.array([
    [210, 230, 190, 250],
    [220, 260, 200, 270],
    [250, 290, 230, 310]])

# task a
print(np.sum(revenue, axis=1))

# task b
print(np.mean(revenue, axis=0))

# task c
print(revenue[2]*[1.05,1.03,1.08,1.02])

# task d
print(revenue[revenue > 250])

[ 880  950 1080]
[226.66666667 260.         206.66666667 276.66666667]
[262.5 298.7 248.4 316.2]
[260 270 290 310]


In [ ]:
## Task 7 Questions

# Create the following DataFrame:

data = {
    "employee": ["Anna", "Erik", "Mia", "Leo", "Sara", "Tom"],
    "department": ["Finance", "Marketing", "Finance", "IT", "Marketing", "IT"],
    "salary": [4500, 4000, 4800, 5200, 3900, 5100],
    "years_exp": [5, 3, 7, 10, 2, 8],
    "performance_score": [4.2, 3.8, 4.5, 4.0, 3.5, 4.9]
}
# a) Add a new column salary_per_year_exp computed as salary / years_exp. Round to the nearest integer.

# b) Sort the DataFrame by performance_score in descending order and print the top 3 employees.

# c) Using .loc, select all employees in the Finance department with a performance score above 4.0. Print the result.

# d) Rename the column years_exp to experience_years using the .rename() method.

# e) Using .iloc, select and print the salary and performance score columns for the first four employees.

In [16]:
## Task 7 Solutions

import pandas as pd

data = {
    "employee": ["Anna", "Erik", "Mia", "Leo", "Sara", "Tom"],
    "department": ["Finance", "Marketing", "Finance", "IT", "Marketing", "IT"],
    "salary": [4500, 4000, 4800, 5200, 3900, 5100],
    "years_exp": [5, 3, 7, 10, 2, 8],
    "performance_score": [4.2, 3.8, 4.5, 4.0, 3.5, 4.9]
}

# task a
data = pd.DataFrame(data)
data["salary_per_year_exp"] = round(data["salary"] / data["years_exp"],0)

# task b
sorted_values = data.sort_values(by=["performance_score"], ascending=False)
print(sorted_values[0:3])

# task c
# Here we apply two masks to filter with
finance = data["department"] == "Finance"
high_score = data["performance_score"] > 4.0
print(data.loc[finance & high_score])

# task d
new_data = data.rename(columns={"years_exp" : "experience_years"})
# print(new_data) <- results can be printed using this (not asked for in instructions)

# task e
print(data.iloc[0:4,[2,4]])


  employee department  salary  years_exp  performance_score  \
5      Tom         IT    5100          8                4.9   
2      Mia    Finance    4800          7                4.5   
0     Anna    Finance    4500          5                4.2   

   salary_per_year_exp  
5                638.0  
2                686.0  
0                900.0  
  employee department  salary  years_exp  performance_score  \
0     Anna    Finance    4500          5                4.2   
2      Mia    Finance    4800          7                4.5   

   salary_per_year_exp  
0                900.0  
2                686.0  
   salary  performance_score
0    4500                4.2
1    4000                3.8
2    4800                4.5
3    5200                4.0


In [ ]:
## Task 8 Questions
# A company records daily website traffic over four weeks. Generate the data by running the following script first:

import numpy as np
import pandas as pd

rng = np.random.default_rng(seed=123)
days = pd.date_range(start="2025-01-06", periods=28, freq="D")
visitors = rng.integers(200, 600, size=28)
conversion_rate = rng.uniform(0.02, 0.08, size=28).round(4)
avg_order_value = rng.normal(50, 10, size=28).round(2)

# Using this generated data, perform the following:

# a) Create a DataFrame with columns: date, visitors, conversion_rate, and avg_order_value. Set date as the index.

# b) Compute two new columns: conversions (= visitors × conversion_rate, rounded to the nearest integer) and daily_revenue (= conversions × avg_order_value).

In [ ]:
## Task 8 Solutions

import numpy as np
import pandas as pd

rng = np.random.default_rng(seed=123)
days = pd.date_range(start="2025-01-06", periods=28, freq="D")
visitors = rng.integers(200, 600, size=28)
conversion_rate = rng.uniform(0.02, 0.08, size=28).round(4)
avg_order_value = rng.normal(50, 10, size=28).round(2)


# task a
data = pd.DataFrame({"date": days,
                     "visitors": visitors,
                     "conversion_rate": conversion_rate,
                     "avg_order_value": avg_order_value})
data = data.set_index("date")


# task b
data["conversions"] = round(data["visitors"] * data["conversion_rate"],0).astype(int)
data["daily_revenue"] = data["conversions"] * data["avg_order_value"]
print(data)

